version: '3.9'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/local/app
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some-long-secure-password
      POSTGRES_DB: photo_management_development
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some-long-secure-password
      POSTGRES_DB: photo_management_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
